<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Create todo_items table.
 * Analogous to an EF Core migration generated by `dotnet ef migrations add`.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('todo_items', function (Blueprint $table) {
            $table->id();                                          // bigint PK, auto-increment
            $table->string('title', 200);
            $table->text('description')->nullable();
            $table->boolean('is_completed')->default(false);
            $table->timestamps();                                  // created_at + updated_at
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('todo_items');
    }
};
